# Generated by AgentSoma's release workflow; do not edit version or checksum independently.
require "digest"
require "json"

class Agentsoma < Formula
  desc "Eyes and hands for agents operating a real iPhone"
  homepage "https://github.com/HughLee824/AgentSoma"
  url "https://github.com/HughLee824/AgentSoma/releases/download/v0.1.0/agentsoma-0.1.0-macos-arm64.tar.gz"
  version "0.1.0"
  sha256 "c2eb4f1ee1e2c61cf05bfae46076f38d18c3385a6b0a5ab2c9181ed933fec80d"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sequoia

  # The signed CLI and Runner manifest must remain byte-for-byte paired.
  skip_clean "libexec"

  def install
    libexec.install "bin", "libexec"
    bin.install_symlink libexec/"bin/agentsoma"
    prefix.install "README.md", "LICENSE", "build-info.json"
    (pkgshare/"licenses").install "licenses/SwiftArgumentParser.txt"
  end

  def caveats
    <<~EOS
      Prepare an iPhone with: agentsoma setup --device <UDID>
      Device setup requires full Xcode and your own Apple development signing.
      Install and upgrade do not compile or sign the Runner, or access your iPhone.
      After an upgrade, disconnect old sessions and rerun setup if requested.
    EOS
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/agentsoma --version").strip
    runner = libexec/"libexec/agentsoma/runner"
    manifest = JSON.parse((runner/"manifest.json").read)
    assert_equal version.to_s, manifest.fetch("releaseVersion")
    assert_equal manifest.fetch("cliSHA256"), Digest::SHA256.file(libexec/"bin/agentsoma").hexdigest
    manifest.fetch("files").each do |name, expected|
      assert_equal expected, Digest::SHA256.file(runner/name).hexdigest, "Changed Runner file: #{name}"
    end
  end
end
